# Generated by Django 2.0 on 2018-01-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('suggested_at', models.DateField(null=True)),
                ('inviting_score', models.IntegerField(null=True)),
                ('guest_score', models.IntegerField(null=True)),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to='liga.Team')),
                ('inviting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviting_matches', to='liga.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Team')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviting_score', models.IntegerField(null=True)),
                ('guest_score', models.IntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Match')),
                ('suggesting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.Team')),
            ],
        ),
    ]
