# Generated by Django 2.0 on 2018-01-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_match_playerinvite_scoreproposition_teamrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
