# Generated by Django 2.0 on 2018-01-24 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0006_auto_20180122_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreproposition',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='guest_proposition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_g', to='liga.ScoreProposition'),
        ),
        migrations.AddField(
            model_name='match',
            name='host_proposition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_h', to='liga.ScoreProposition'),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
